name: Cross Check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  cross-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.89.0
        with:
          targets: riscv32imc-unknown-none-elf
      - run: cargo check -p kernel --lib --target riscv32imc-unknown-none-elf
